### ISSUE TITLE
Fail when testing with live credentials "CHBInterstitial FAILED (CHBShowErrorCodeInternal)"

### ISSUE THREAD

**Issue by rob-barber** [ChartBoost/ios-sdk-example#16] opened 2020-11-24 19:34 UTC
This is an underlying issue with the Chartboost iOS SDK. When attempting to show a cached interstitial the operation fails with a "CHBShowErrorCodeInternal" error.

This does not occur when in "test mode" or using the provided App ID/App Signature within the project. It only occurs when using a published App ID/App Signature.

Steps to reproduce:
1. Update the App-ID + App Signature to using live/published values.
2. Build using an iOS 14.2 device (could be affecting others but this is what I used).
3. Deploy/Run to a physical device.
4. Tap the "Cache Interstitial" button.
5. Tap "Show Interstitial" button.

**Comment by daniel-barros** [comment] 2020-11-25 09:46
Hi @rob-barber thanks for the feedback!
We think this may be due to a faulty ad creative, and shouldn't be widespread. Could you try again and see if it is still happening? If that's the case please let me know and we'll file a ticket and gather more information.

**Comment by rob-barber** [comment] 2020-11-25 13:20
The issue is still occurring. See the printout of the console below:

Chartboost (I) | Showing interstitial ad.
Chartboost ⚠️  | Failed to parse ad template: missing mustache parameter: {{ video_landscape }}.
Chartboost (I) | Failed to parse ad template: Missing mustache parameters.
Chartboost (I) | Removed ad.
didShowAd: CHBInterstitial FAILED (CHBShowErrorCodeInternal)

Not sure what “missing mustache parameter: {{ video_landscape }}” means but I only see it when using live credentials.

Rob

**Comment by daniel-barros** [comment] 2020-11-25 14:37
Thanks for sharing the logs @rob-barber. 
I can confirm this is a backend issue known to us that affects some creatives, our team is working on it already and I expect a fix in the coming days.
Neither the SDK nor the example app are responsible for this so I'll close the issue.
Please feel free to reopen later if you find this or any other problem. Thanks again for all the feedback 🙂

**Closed by daniel-barros** 2020-11-25 14:37 UTC
